[package]
name = "selendra-node-primitives"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
futures = "0.3.12"
selendra-primitives = { path = "../../../primitives" }
selendra-statement-table = { path = "../../statement-table" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
runtime_primitives = { package = "sp-runtime", git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-consensus-vrf = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-maybe-compressed-blob  = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
selendra-parachain = { path = "../../parachain", default-features = false }
schnorrkel = "0.9.1"
thiserror = "1.0.22"
serde = { version = "1.0.123", features = ["derive"] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = "0.6.0"
