[package]
name = "indracore-node-primitives"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
futures = "0.3.12"
indracore-primitives = { path = "../../../primitives" }
indracore-statement-table = { path = "../../statement-table" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
runtime_primitives = { package = "sp-runtime", git = "https://github.com/selendra/substrate", branch = "v2.0.4", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-consensus-vrf = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
schnorrkel = "0.9.1"
thiserror = "1.0.22"
