[package]
name = "selendra-rpc-primitives-debug"
version = '0.1.0'
authors = ["Selendra <info@selendra.org>"]
edition = '2018'

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
hex = { version = "0.4", features = ["serde"], optional = true}
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
ethereum = { version = "0.7.1", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.11.0", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate.git", branch = "0.1.0-tn3", default-features = false }
sp-api = { git = "https://github.com/selendra/substrate.git", branch = "0.1.0-tn3", default-features = false }
sp-io = { git = "https://github.com/selendra/substrate.git", branch = "0.1.0-tn3", default-features = false }
sp-std = { git = "https://github.com/selendra/substrate.git", branch = "0.1.0-tn3", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate.git", branch = "0.1.0-tn3", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"ethereum/std",
	"ethereum-types/std",
	"serde",
	"serde_json",
	"hex"
]
