[package]
name = "indracore-node-core-chain-api"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "master" }
indracore-primitives = { path = "../../../primitives" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
futures = { version = "0.3.12", features = ["thread-pool"] }
maplit = "1.0.2"
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
