[package]
name = "selendra-node-core-provisioner"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
futures = "0.3.12"
tracing = "0.1.25"
thiserror = "1.0.23"
selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
futures-timer = "3.0.2"

[dev-dependencies]
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
