[package]
name = "selendra-node-core-backing"
version = "0.1.4"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.29"
thiserror = "1.0.30"
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
erasure-coding = { package = "selendra-erasure-coding", path = "../../../modules/erasure-coding" }
statement-table = { package = "selendra-statement-table", path = "../../../modules/statement-table" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }
futures = { version = "0.3.17", features = ["thread-pool"] }
assert_matches = "1.4.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
