[package]
name = "indracore"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
description = "Implementation of a in Indracore node in Rust based on the Substrate framework."
edition = "2018"

[[bin]]
name = "indracore"
path = "src/main.rs"

[dependencies]
cli = { package = "indracore-cli", path = "cli" }
color-eyre = "0.5.10"
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

[badges]
maintenance = { status = "actively-developed" }

[features]
runtime-benchmarks=["cli/runtime-benchmarks"]
try-runtime = ["cli/try-runtime"]