[package]
name = "selendra"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Implementation of selendra node in Rust based on the Substrate framework."
license = "GPL-3.0-only"

[[bin]]
name = "selendra"
path = "src/main.rs"

[dependencies]
selendra-cli = { path = "cli" }
color-eyre = { version = "0.5.11", default-features = false }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

[dev-dependencies]
assert_cmd = "1.0.2"
nix = "0.19.1"
tempfile = "3.2.0"

[features]
runtime-benchmarks= [ "selendra-cli/runtime-benchmarks" ]
try-runtime = [ "selendra-cli/try-runtime" ]