[package]
name = "selendra-availability-distribution"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.29"
parity-scale-codec = { version = "2.3.1", features = ["std"] }
selendra-primitives = { path = "../../../primitives" }
selendra-erasure-coding = { path = "../../../modules/erasure-coding" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-network-protocol = { path = "../../network/protocol" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-primitives = { path = "../../primitives" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", features = ["std"] }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
thiserror = "1.0.30"
rand = "0.8.3"
derive_more = "0.99.11"
lru = "0.7.0"

[dev-dependencies]
selendra-subsystem-testhelpers = { package = "selendra-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", features = ["std"] }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
