[package]
name = "indracore-availability-distribution"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
parity-scale-codec = { version = "2.0.0", features = ["std"]  }
indracore-primitives = { path = "../../../../primitives" }
indracore-erasure-coding = { path = "../../../erasure-coding" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-network-protocol = { path = "../../network/protocol" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-node-core-runtime-api = { path = "../../core/runtime-api" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.4", features = ["std"]  }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
thiserror = "1.0.23"
rand = "0.8.3"
lru = "0.6.5"

[dev-dependencies]
indracore-subsystem-testhelpers = { package = "indracore-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.4", features = ["std"] }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-tracing = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sc-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sc-network = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
maplit = "1.0"
smallvec = "1.6.1"
