[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
# Substrate deps
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }

# Selendra deps
selendra-primitives = { path = "../../../../../primitives" }
selendra-runtime = { path = "../../../../../runtime/selendra" }

# Other deps
futures = { version = "0.3.8", features = ["compat"] }
codec = { package = "parity-scale-codec", version = "2.0.0", features = [ "derive" ] }
tracing = "0.1.25"
async-trait = "0.1.42"
dyn-clone = "1.0.4"

[dev-dependencies]
# Substrate deps
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }

# Cumulus dependencies
cumulus-test-runtime = { path = "../../../test/runtime" }
cumulus-test-client = { path = "../../../test/client" }
cumulus-test-service = { path = "../../../test/service" }
cumulus-primitives-core = { path = "../../../primitives/core" }

# Selendra deps
selendra-test-client = { path = "../../../../../bin/test/client" }

# Other deps
tokio = { version = "0.2.21", features = ["macros"] }
futures-timer = "3.0.2"
