[package]
name = "selendra-availability-recovery"
version = "0.1.2"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
lru = "0.6.1"
rand = "0.8.3"
thiserror = "1.0.21"
tracing = "0.1.26"

selendra-erasure-coding = { path = "../../../modules/erasure-coding" }
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-network-protocol = { path = "../../network/protocol" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.8.4"
futures-timer = "3.0.2"
log = "0.4.11"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

selendra-subsystem-testhelpers = { package = "selendra-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
