[package]
name = "selendra-collator-protocol"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
always-assert = "0.1.2"
futures = "0.3.12"
futures-timer = "3"
thiserror = "1.0.23"
tracing = "0.1.25"

sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-network-protocol = { path = "../../network/protocol" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }

[dev-dependencies]
log = "0.4.13"
env_logger = "0.8.2"
assert_matches = "1.4.0"

sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2", features = ["std"] }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }

selendra-subsystem-testhelpers = { package = "selendra-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
