[package]
name = "selendra-statement-distribution"
version = "0.1.4"
authors = ["Selendra info@selendra.org"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.29"
arrayvec = "0.5.2"
indexmap = "1.7.0"
derive_more = "0.99.11"
thiserror = "1.0.26"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

selendra-primitives = { path = "../../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-network-protocol = { path = "../../network/protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
futures-timer = "3.0.2"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
