[package]
name = "selendra-service"
version =  "0.1.0-tn5"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
# Substrate Client
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
babe = { package = "sc-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
beefy-primitives = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "polkadot-v0.9.7" }
beefy-gadget = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "polkadot-v0.9.7" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", default-features = false }
telemetry = { package = "sc-telemetry", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
consensus_common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
grandpa_primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# Substrate Pallets
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-mmr-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# Substrate Other
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# External Crates
futures = "0.3.15"
hex-literal = "0.3.1"
tracing = "0.1.26"
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.23"
kvdb = "0.9.0"
kvdb-rocksdb = { version = "0.11.0", optional = true }
serde_json = "1.0.64"

# Selendra
selendra-node-core-parachains-inherent = { path = "../../modules/node/core/parachains-inherent" }
selendra-overseer = { path = "../../modules/node/overseer" }
selendra-parachain = { path = "../../modules/parachain" }
selendra-primitives = { path = "../../primitives" }
selendra-client = { path = "../client" }
selendra-node-primitives = { path = "../../modules/node/primitives" }
selendra-rpc = { path = "../rpc" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../modules/node/subsystem" }
selendra-node-subsystem-util = { path = "../../modules/node/subsystem-util" }
selendra-runtime-parachains = { path = "../../modules/parachain/runtime-parachains" }

# Selendra Runtimes
selendra-runtime = { path = "../../runtime/selendra" }

# Selendra Subsystems
selendra-availability-bitfield-distribution = { path = "../../modules/node/network/bitfield-distribution", optional = true }
selendra-availability-distribution = { path = "../../modules/node/network/availability-distribution", optional = true }
selendra-availability-recovery = { path = "../../modules/node/network/availability-recovery", optional = true }
selendra-collator-protocol = { path = "../../modules/node/network/collator-protocol", optional = true }
selendra-gossip-support = { path = "../../modules/node/network/gossip-support", optional = true }
selendra-network-bridge = { path = "../../modules/node/network/bridge", optional = true }
selendra-node-collation-generation = { path = "../../modules/node/collation-generation", optional = true }
selendra-node-core-av-store = { path = "../../modules/node/core/av-store", optional = true }
selendra-node-core-backing = { path = "../../modules/node/core/backing", optional = true }
selendra-node-core-bitfield-signing = { path = "../../modules/node/core/bitfield-signing", optional = true }
selendra-node-core-candidate-validation = { path = "../../modules/node/core/candidate-validation", optional = true }
selendra-node-core-chain-api = { path = "../../modules/node/core/chain-api", optional = true }
selendra-node-core-provisioner = { path = "../../modules/node/core/provisioner", optional = true }
selendra-node-core-runtime-api = { path = "../../modules/node/core/runtime-api", optional = true }
selendra-statement-distribution = { path = "../../modules/node/network/statement-distribution", optional = true }
selendra-approval-distribution = { path = "../../modules/node/network/approval-distribution", optional = true }
selendra-node-core-approval-voting = { path = "../../modules/node/core/approval-voting", optional = true }

[dev-dependencies]
selendra-test-client = { path = "../test/client" }
env_logger = "0.8.2"

[features]
default = ["db", "full-node"]
db = ["service/db"]
full-node = [
	"selendra-node-core-av-store",
	"selendra-node-core-approval-voting",
	"selendra-availability-bitfield-distribution",
	"selendra-availability-distribution",
	"selendra-availability-recovery",
	"selendra-collator-protocol",
	"selendra-gossip-support",
	"selendra-network-bridge",
	"selendra-node-collation-generation",
	"selendra-node-core-backing",
	"selendra-node-core-bitfield-signing",
	"selendra-node-core-candidate-validation",
	"selendra-node-core-chain-api",
	"selendra-node-core-provisioner",
	"selendra-node-core-runtime-api",
	"selendra-statement-distribution",
	"selendra-approval-distribution",
	"sc-finality-grandpa-warp-sync",
	"kvdb-rocksdb"
]

runtime-benchmarks = [
	"selendra-runtime/runtime-benchmarks",
]
try-runtime = [
	"selendra-runtime/try-runtime"
]
light-node = []
