[workspace]
members = [
	# "bin/cli",
	# "primitives",
	# "primitives/core-primitives",

	# "runtime/common",
	# "runtime/common/slot_range_helper",
	# "runtime/selendra",

	# "node/client",
	# "node/collation-generation",
	# "node/core/approval-voting",
	# "node/core/av-store",
	# "node/core/backing",
	# "node/core/bitfield-signing",
	# "node/core/candidate-validation",
	# "node/core/chain-api",
	# "node/core/chain-selection",
	# "node/core/dispute-coordinator",
	# "node/core/dispute-participation",
	# "node/core/parachains-inherent",
	# "node/core/provisioner",
	# "node/core/pvf",
	# "node/core/runtime-api",
	# "node/network/approval-distribution",
	# "node/network/bridge",
	# "node/network/protocol",
	# "node/network/statement-distribution",
	# "node/network/bitfield-distribution",
	# "node/network/availability-distribution",
	# "node/network/availability-recovery",
	# "node/network/collator-protocol",
	# "node/network/gossip-support",
	# "node/network/dispute-distribution",
	# "node/overseer",
	# "node/overseer/overseer-gen",
	# "node/overseer/overseer-gen/proc-macro",
	# "node/primitives",
	# "node/service",
	# "node/subsystem",
	# "node/subsystem-types",
	# "node/subsystem-test-helpers",
	# "node/subsystem-util",
	# "node/jaeger",
	# "node/metrics",
	# "node/metered-channel",
		
	# "modules/erasure-coding",
	# "modules/statement-table",
	# "modules/xcm",
	# "modules/xcm/xcm-builder",
	# "modules/xcm/xcm-executor",
	# "modules/xcm/pallet-xcm",
	# "modules/xcm/pallet-xcm-benchmarks",
	# "modules/xcm/procedural",
	
	"frame/dynamic-fee",
	"frame/ethereum",
	"frame/evm",
	"frame/evm/precompile/sha3fips",
	"frame/evm/precompile/simple",
	"frame/evm/precompile/modexp",
	"frame/evm/precompile/ed25519",
	"frame/evm/precompile/bn128",
	"frame/evm/precompile/blake2",
	"frame/evm/precompile/dispatch",
	"frame/evm/precompile/curve25519",
	"client/consensus",
	"client/rpc-core",
	"client/rpc",
	"client/db",
	"client/mapping-sync",
	"primitives/consensus",
	"primitives/evm",
	"primitives/rpc",
	"primitives/self-contained",
	"template/node",
	"template/runtime",
]

[patch.crates-io]
evm = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11"}
evm-runtime = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
evm-gasometer = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info" }

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"
