[workspace]
members = [
	"bin",
	"runtime/selendra",
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"