[workspace]
members = [
    # "primitives",
	# "rpc",
    # "parachains/parachain",
    # "parachains/runtime-parachains",
    # "subsystems/subsystem",
    # "subsystems/collation-generation",
	# "subsystems/core/approval-voting",
	# "subsystems/core/av-store",
	# "subsystems/core/backing",
	# "subsystems/core/bitfield-signing",
	# "subsystems/core/candidate-selection",
	# "subsystems/core/candidate-validation",
	# "subsystems/core/chain-api",
	# "subsystems/core/proposer",
	# "subsystems/core/provisioner",
	# "subsystems/core/runtime-api",
	# "subsystems/network/approval-distribution",
	# "subsystems/network/bridge",
	# "subsystems/network/protocol",
	# "subsystems/network/statement-distribution",
	# "subsystems/network/bitfield-distribution",
	# "subsystems/network/availability-distribution",
	# "subsystems/network/availability-recovery",
	# "subsystems/network/collator-protocol",
	# "subsystems/network/gossip-support",
	# "subsystems/overseer",
	# "subsystems/primitives",
	# "subsystems/subsystem",
	# "subsystems/subsystem/dispatch-gen",
	# "subsystems/subsystem-test-helpers",
	# "subsystems/subsystem-util",
	# "subsystems/jaeger",
	# "subsystems/metered-channel",
	"bin",
	"node",
	"runtime/common",
	"runtime/indracore"
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Indracore runtime requires unwinding.
panic = "unwind"