[workspace]
members = [
	"bin",
	"bin/cli",
	"primitives",
	"primitives/core-primitives",
	"runtime/common",
	"runtime/common/slot_range_helper",
	"runtime/selendra",
	"modules/erasure-coding",
	"modules/statement-table",
	"modules/xcm",
	"modules/xcm/xcm-builder",
	"modules/xcm/xcm-executor",
	"modules/xcm/pallet-xcm",
	"modules/node/collation-generation",
	"modules/node/core/approval-voting",
	"modules/node/core/av-store",
	"modules/node/core/backing",
	"modules/node/core/bitfield-signing",
	"modules/node/core/candidate-selection",
	"modules/node/core/candidate-validation",
	"modules/node/core/chain-api",
	"modules/node/core/parachains-inherent",
	"modules/node/core/provisioner",
	"modules/node/core/pvf",
	"modules/node/core/runtime-api",
	"modules/node/network/approval-distribution",
	"modules/node/network/bridge",
	"modules/node/network/protocol",
	"modules/node/network/statement-distribution",
	"modules/node/network/bitfield-distribution",
	"modules/node/network/availability-distribution",
	"modules/node/network/availability-recovery",
	"modules/node/network/collator-protocol",
	"modules/node/network/gossip-support",
	"modules/node/overseer",
	"modules/node/primitives",
	"modules/node/subsystem",
	"modules/node/subsystem/dispatch-gen",
	"modules/node/subsystem-test-helpers",
	"modules/node/subsystem-util",
	"modules/node/jaeger",
	"modules/node/metered-channel",
	"modules/parachain/test-parachains",
	"modules/parachain/test-parachains/adder",
	"modules/parachain/test-parachains/adder/collator",
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"