[workspace]
members = [
	"bin/service",
	"runtime/selendra",
	"bin",
	"bin/cli",
	# "bin/rpc",
	# "primitives",
	# "primitives/core-primitives",
	# "runtime/common",
	# "runtime/common/slot_range_helper",
	# "modules/erasure-coding",
	# "modules/statement-table",
	# "modules/xcm",
	# "modules/xcm/xcm-builder",
	# "modules/xcm/xcm-executor",
	# "modules/xcm/pallet-xcm",
	# "modules/node/collation-generation",
	# "modules/node/core/approval-voting",
	# "modules/node/core/av-store",
	# "modules/node/core/backing",
	# "modules/node/core/bitfield-signing",
	# "modules/node/core/candidate-validation",
	# "modules/node/core/chain-api",
	# "modules/node/core/parachains-inherent",
	# "modules/node/core/provisioner",
	# "modules/node/core/pvf",
	# "modules/node/core/runtime-api",
	# "modules/node/network/approval-distribution",
	# "modules/node/network/bridge",
	# "modules/node/network/protocol",
	# "modules/node/network/statement-distribution",
	# "modules/node/network/bitfield-distribution",
	# "modules/node/network/availability-distribution",
	# "modules/node/network/availability-recovery",
	# "modules/node/network/collator-protocol",
	# "modules/node/network/gossip-support",
	# "modules/node/overseer",
	# "modules/node/primitives",
	# "modules/node/subsystem",
	# "modules/node/subsystem/dispatch-gen",
	# "modules/node/subsystem-test-helpers",
	# "modules/node/subsystem-util",
	# "modules/node/jaeger",
	# "modules/node/metered-channel",
	# "modules/cumulus/client/cli",
	# "modules/cumulus/client/consensus/aura",
	# "modules/cumulus/client/consensus/common",
	# "modules/cumulus/client/consensus/relay-chain",
	# "modules/cumulus/client/network",
	# "modules/cumulus/client/pov-recovery",
	# "modules/cumulus/client/service",
	# "modules/cumulus/pallets/aura-ext",
	# "modules/cumulus/pallets/collator-selection",
	# "modules/cumulus/pallets/dmp-queue",
	# "modules/cumulus/pallets/parachain-system",
	# "modules/cumulus/pallets/xcm",
	# "modules/cumulus/pallets/xcmp-queue",
	# "modules/cumulus/pallets/parachain-info",
	# "modules/cumulus/primitives/core",
	# "modules/cumulus/primitives/parachain-inherent",
	# "modules/cumulus/primitives/utility",
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"