[package]
name = "indracore-node-primitives"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
futures = "0.3.12"
schnorrkel = "0.9.1"
thiserror = "1.0.22"
serde = { version = "1.0.123", features = ["derive"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

runtime_primitives = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-vrf = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "master" }

indracore-primitives = { path = "../../primitives" }
indracore-statement-table = { path = "../statement-table" }
indracore-parachain = { path = "../../parachains/parachain", default-features = false }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = "0.5.0"
