[package]
name = "selendra-statement-table"
version =  "0.1.0-tn4"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
primitives = { package = "selendra-primitives", path = "../../primitives" }
