[package]
name = "orml-tokens"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Fungible tokens module that implements `MultiCurrency` trait."
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
max-encoded-len = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-std = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
frame-support = {  git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
frame-system = {  git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
orml-traits = { path = "../traits", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
pallet-treasury = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
# Patch doesn't work as `pallet-elections-phragmen` is now 4.0.0 version. Revert `rev` to `statemint` branch after
# other `statemint` dependencies upgraded.
pallet-elections-phragmen = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"orml-traits/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
