[package]
name = "selendra-collator"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "selendra-collator"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
exit-future = "0.1.4"
futures = { version = "0.3.1", features = ["compat"] }
log = "0.4.8"
parking_lot = "0.10.2"
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "2.0.0" }
structopt = "0.3.3"
serde = { version = "1.0.101", features = ["derive"] }
hex-literal = "0.2.1"
async-trait = "0.1.42"
jsonrpc-core = "15.1.0"

# Parachain runtimes
selendra-parachain-runtime = { path = "../runtime" }
selendra-parachain-common = { path = "../common" }
selendra-primitives = { path = "../../primitives" }

# Substrate dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Cumulus dependencies
cumulus-client-cli = { path = "../../modules/cumulus/client/cli" }
cumulus-client-consensus-aura = { path = "../../modules/cumulus/client/consensus/aura" }
cumulus-client-consensus-relay-chain = { path = "../../modules/cumulus/client/consensus/relay-chain" }
cumulus-client-consensus-common = { path = "../../modules/cumulus/client/consensus/common" }
cumulus-client-collator = { path = "../../modules/cumulus/client/collator" }
cumulus-client-service = { path = "../../modules/cumulus/client/service" }
cumulus-client-network = { path = "../../modules/cumulus/client/network" }
cumulus-primitives-core = { path = "../../modules/cumulus/primitives/core" }
cumulus-primitives-parachain-inherent = { path = "../../modules/cumulus/primitives/parachain-inherent" }

# Selendra dependencies
selendra-service = { path = "../../bin/service" }
selendra-cli = { path = "../../bin/cli" }
selendra-parachain = { path = "../../modules/parachain" }
selendra-runtime = { path = "../../runtime/selendra" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tempfile = "3.2.0"
tokio = { version = "0.2.13", features = ["macros"] }

# Selendra dependencies
selendra-runtime-common = { path = "../../runtime/common" }
selendra-test-runtime = { path = "../../runtime/test-runtime" }
selendra-test-client = { path = "../../bin/test/client" }
selendra-test-service = { path = "../../bin/test/service" }

# Substrate dependencies
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "master" }
substrate-test-client = { git = "https://github.com/paritytech/substrate", branch = "master" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = []
runtime-benchmarks = [
	'selendra-service/runtime-benchmarks',
	'selendra-parachain-runtime/runtime-benchmarks',

]