[package]
name = "pallet-xcm"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"


[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

sp-std = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-runtime = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
frame-support = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
frame-system = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }

xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"xcm/std",
]
runtime-benchmarks = []