[package]
name = "cumulus-primitives-utility"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }

# Selendra dependencies
selendra-parachain = { path = "../../../../modules/parachain", default-features = false }
selendra-primitives = { path = "../../../../primitives", default-features = false }
selendra-core-primitives = { path = "../../../../primitives/core-primitives", default-features = false }
xcm = { path = "../../../../modules/xcm", default-features = false }

# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"selendra-core-primitives/std",
	"selendra-parachain/std",
	"selendra-primitives/std",
	"cumulus-primitives-core/std",
]
