[package]
name = "indracore-node-collation-generation"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
thiserror = "1.0.23"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }

indracore-erasure-coding = { path = "../erasure-coding" }
indracore-node-primitives = { path = "../primitives" }
indracore-node-subsystem = { path = "../subsystem" }
indracore-node-subsystem-util = { path = "../subsystem-util" }
indracore-primitives = { path = "../../primitives" }

[dev-dependencies]
indracore-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
