[package]
name = "fc-mapping-sync"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Mapping sync logic for Frontier."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sc-client-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
sp-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
fp-consensus = { path = "../../primitives/consensus" }
fc-consensus = { path = "../consensus" }
fc-db = { path = "../db" }
fp-rpc = { path = "../../primitives/rpc" }
futures = { version = "0.3.1", features = ["compat"] }
futures-timer = "3.0.1"
log = "0.4.8"
