[package]
name = "selendra-gossip-support"
version = "0.1.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

selendra-node-network-protocol = { path = "../protocol" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-primitives = { path = "../../../primitives" }

futures = "0.3.15"
rand = { version = "0.8.3", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
tracing = "0.1.26"

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"], branch = "polkadot-v0.9.10" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
