[package]
name = "indracore-gossip-support"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }

indracore-node-network-protocol = { path = "../protocol" }
indracore-node-subsystem = { path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-primitives = { path = "../../../primitives" }

futures = "0.3.8"
tracing = "0.1.25"
