[package]
name = "test-parachains"
version = "0.1.0-tn3"
authors = ["Selendra <info@selendra.org>"]
description = "Integration tests using the test-parachains"
edition = "2018"

[dependencies]
tiny-keccak = "2.0.2"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

parachain = { package = "selendra-parachain", path = ".." }
adder = { package = "test-parachain-adder", path = "adder" }
halt = { package = "test-parachain-halt", path = "halt" }

[dev-dependencies]
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }

[features]
default = [ "std" ]
std = [
	"adder/std",
	"halt/std",
]
