[package]
name = "indracore-node-jaeger"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Indracore Jaeger primitives"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false }
async-std = "1.8.0"
mick-jaeger = "0.1.4"
lazy_static = "1.4"
parking_lot = "0.11.1"
indracore-primitives = { path = "../../primitives" }
sc-network = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
indracore-node-primitives = { path = "../primitives" }
thiserror = "1.0.23"
log = "0.4.13"

