
[package]
name = "xcm-executor-integration-tests"
version = "0.1.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Integration tests for the XCM Executor"


[dependencies]
frame-support = { git = "https://github.com/paritytech/substrate" , default-features = false , branch = "polkadot-v0.9.14" }
frame-system = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v0.9.14" }
futures = "0.3.17"
pallet-xcm = { path = "../../pallet-xcm" }
selendra-test-client = { path = "../../../node/test/client" }
selendra-test-runtime = { path = "../../../runtime/test-runtime" }
selendra-test-service = { path = "../../../node/test/service" }
sp-consensus = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v0.9.14" }
sp-keyring = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v0.9.14" }
sp-runtime = { git = "https://github.com/paritytech/substrate" , default-features = false , branch = "polkadot-v0.9.14" }
sp-state-machine = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v0.9.14" }
xcm = { path = "../..", default-features = false }
xcm-executor = { path = ".." }
sp-tracing = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v0.9.14" }

[features]
default = ["std"]
std = [
	"xcm/std",
	"sp-runtime/std",
	"frame-support/std",
]