[package]
name = "cumulus-primitives-parachain-inherent"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-inherents = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-core = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sc-client-api = { git = "https://github.com/selendra/substrate", optional = true , branch = "0.1.0-tn4" }
sp-runtime = { git = "https://github.com/selendra/substrate", optional = true , branch = "0.1.0-tn4" }
sp-std = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-state-machine = { git = "https://github.com/selendra/substrate", optional = true , branch = "0.1.0-tn4" }
sp-trie = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-api = { git = "https://github.com/selendra/substrate", optional = true , branch = "0.1.0-tn4" }

# Selendra dependencies
selendra-client = { path = "../../../../bin/client", optional = true }

# Cumulus dependencies
cumulus-primitives-core = { path = "../core", default-features = false }

# Other dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [ "derive" ] }
tracing = { version = "0.1.22", optional = true }
async-trait = { version = "0.1.42", optional = true }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"cumulus-primitives-core/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-trie/std",
	"sp-std/std",
	"sp-state-machine",
	"tracing",
	"sp-runtime",
	"sc-client-api",
	"sp-api",
	"selendra-client",
]
