[package]
name = "selendra-node-core-parachains-inherent"
version = "0.1.9"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[dependencies]
futures = "0.3.17"
futures-timer = "3.0.2"
tracing = "0.1.29"
thiserror = "1.0.30"
async-trait = "0.1.51"
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-primitives = { path = "../../../primitives" }