[package]
name = "selendra-node-core-parachains-inherent"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
tracing = "0.1.31"
thiserror = "1.0.30"
async-trait = "0.1.52"
selendra-node-subsystem = { path = "../../subsystem" }
selendra-primitives = { path = "../../../primitives" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
