[package]
name = "indracore-parachain"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
description = "Types and utilities for creating and working with parachains"
edition = "2018"

[dependencies]
derive_more = "0.99.11"
parking_lot = { version = "0.11.1", optional = true }
log = { version = "0.4.11", optional = true }
futures = { version = "0.3.8", optional = true }
static_assertions = { version = "1.1", optional = true }
libc = { version = "0.2.81", optional = true }
thiserror = { version = "1.0.22", optional = true }
serde = { version = "1.0.117", default-features = false, features = [ "derive" ], optional = true }

parity-scale-codec = { version = "2.0.0", default-features = false, features = [ "derive" ] }
parity-util-mem = { version = "0.9.0", optional = true }

sp-std = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }

indracore-core-primitives = { path = "../../primitives/core-primitives", default-features = false }

[target.'cfg(not(any(target_os = "android", target_os = "unknown")))'.dependencies]
shared_memory = { version = "0.11.0", optional = true }
raw_sync = { version = "0.1", optional = true }

[features]
default = ["std"]
wasmtime = [ "sc-executor/wasmtime" ]
wasm-api = []
std = [
	"thiserror",
	"serde/std",
	"shared_memory",
	"raw_sync",
	"parking_lot",
	"log",
	"libc",
	"static_assertions",
	"parity-util-mem",
	"futures",
	"sp-io",
	"sp-std/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-externalities",
	"sc-executor",
	"parity-scale-codec/std",
	"indracore-core-primitives/std",
]