[package]
name = "selendra-node-core-runtime-api"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
memory-lru = "0.1.0"
parity-util-mem = { version = "0.9.0", default-features = false }

sp-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-authority-discovery = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }

selendra-primitives = { path = "../../../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
futures = { version = "0.3.12", features = ["thread-pool"] }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
selendra-node-primitives = { path = "../../primitives" }
