[package]
name = "selendra-node-primitives"
version = "0.2.2"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
bounded-vec = "0.5"
futures = "0.3.21"
schnorrkel = "0.9.1"
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }

selendra-primitives = { path = "../../primitives" }
selendra-parachain = { path = "../../modules/parachain", default-features = false }

parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-consensus-vrf = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = "0.9.2"

[dev-dependencies]
selendra-erasure-coding = { path = "../../modules/erasure-coding" }
