[package]
name = "selendra-node-subsystem-util"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
futures-timer = "3.0.2"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
parking_lot = { version = "0.11.1", optional = true }
pin-project = "1.0.4"
rand = "0.8.3"
streamunordered = "0.5.1"
thiserror = "1.0.23"
tracing = "0.1.25"
lru = "0.6.5"

selendra-node-primitives = { path = "../primitives" }
selendra-node-subsystem = { path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-network-protocol = { path = "../network/protocol" }
selendra-primitives = { path = "../../../primitives" }
metered-channel = { path = "../metered-channel"}

sc-network = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }
substrate-prometheus-endpoint = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn2" }

[dev-dependencies]
assert_matches = "1.4.0"
async-trait = "0.1.42"
env_logger = "0.8.2"
futures = { version = "0.3.12", features = ["thread-pool"] }
log = "0.4.13"
parking_lot = "0.11.1"
selendra-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
