[package]
name = "selendra-node-core-bitfield-signing"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
tracing = "0.1.26"
selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
wasm-timer = "0.2.5"
thiserror = "1.0.23"

[dev-dependencies]
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
