[package]
name = "xcm-simulator"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
description = "Test kit to simulate cross-chain message passing and XCM execution"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
paste = "1.0.6"

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
selendra-core-primitives = { path = "../../../primitives/core-primitives"}
selendra-parachain = { path = "../../parachain" }
selendra-runtime-parachains = { path = "../../parachain/runtime" }
