[package]
name = "indracore-node-core-candidate-validation"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
# tracing-futures = "0.2.4"

sp-core = { package = "sp-core", git = "https://github.com/selendra/substrate", branch = "master" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["bit-vec", "derive"] }

indracore-primitives = { path = "../../../primitives" }
indracore-parachain = { path = "../../../parachain" }
indracore-node-primitives = { path = "../../primitives" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "master" }
futures = { version = "0.3.12", features = ["thread-pool"] }
assert_matches = "1.4.0"
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
