[package]
name = "selendra-node-core-candidate-validation"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.21"
tracing = "0.1.31"

sp-maybe-compressed-blob = { package = "sp-maybe-compressed-blob", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["bit-vec", "derive"] }

selendra-primitives = { path = "../../../primitives" }
selendra-parachain = { path = "../../../modules/parachain" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[target.'cfg(not(any(target_os = "android", target_os = "unknown")))'.dependencies]
selendra-node-core-pvf = { path = "../pvf" }

[dev-dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
futures = { version = "0.3.21", features = ["thread-pool"] }
assert_matches = "1.4.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../primitives/test-helpers" }
