[package]
name = "module-manager"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

frame-support = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
frame-system = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-io = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }
sp-std = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4", default-features = false }

primitives = { package = "selendra-core-primitives", path = "../../../primitives/core-primitives", default-features = false }
module-support = { path = "../support", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
pallet-timestamp = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
orml-currencies = { path = "../../orml/currencies" }
orml-tokens = { path = "../../orml/tokens" }
orml-traits = { path = "../../orml/traits" }
orml-utilities = { path = "../../orml/utilities" }
module-evm = { path = "../evm" }
module-evm-bridge = { path = "../evm-bridge" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"primitives/std",
	"module-support/std",
]
try-runtime = ["frame-support/try-runtime"]
