[package]
name = "cumulus-client-network"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "Cumulus-specific networking protocol"
edition = "2018"

[dependencies]
# Substrate deps
sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-consensus = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-client-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }

# Selendra deps
selendra-primitives = { path = "../../../../primitives" }
selendra-statement-table = { path = "../../../statement-table" }
selendra-node-primitives = { path = "../../../node/primitives" }
selendra-service = { path = "../../../../bin/service" }
selendra-parachain = { path = "../../../parachain" }

# other deps
codec = { package = "parity-scale-codec", version = "2.0.0", features = [ "derive" ] }
futures = { version = "0.3.1", features = ["compat"] }
futures-timer = "3.0.2"
tracing = "0.1.22"
parking_lot = "0.10.2"
derive_more = "0.99.2"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }

# Cumulus deps
cumulus-test-service = { path = "../../test/service" }
cumulus-primitives-core = { path = "../../primitives/core" }

# Selendra deps
selendra-test-client = { path = "../../../../bin/test/client" }

# substrate deps
sc-client-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-consensus = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-cli = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
substrate-test-utils = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-service = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
