[package]
name = "selendra-parachain-common"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Logic which is common to all Statemint variant runtimes"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# External dependencies
codec = { package = 'parity-scale-codec', version = '2.0.0', features = ['derive'], default-features = false }

# Substrate dependencies
sp-consensus-aura = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
sp-std = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
sp-io = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
frame-executive = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
frame-support = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
frame-system = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
pallet-balances = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
sp-runtime = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
sp-core = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
node-primitives = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }

# Selendra dependencies
selendra-runtime-common = { path = "../../runtime/common", default-features = false }
selendra-primitives = { path = "../../primitives",default-features = false }

# Local dependencies
pallet-collator-selection = { path = '../../modules/cumulus/pallets/collator-selection', default-features = false }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-io = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }
pallet-authorship = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = 'https://github.com/selendra/substrate', branch = "0.1.0-tn3" }

[features]
default = ["std"]
std = [
	'codec/std',
	'sp-consensus-aura/std',
	'sp-std/std',
	'sp-io/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'pallet-collator-selection/std',
	'pallet-balances/std',
	'node-primitives/std',
	'selendra-runtime-common/std',
	'selendra-primitives/std',
]