[package]
name = "selendra-rpc-core-debug"
version = '0.1.0'
authors = ["Selendra <info@selendra.org>"]
edition = '2018'


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3", features = ["compat"] }
ethereum-types = "0.11.0"
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
selendra-rpc-primitives-debug = { path = "../../../rpc/debug" }