[package]
name = "selendra-node-subsystem-util"
version = "0.2.2"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.21"
itertools = "0.10"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
pin-project = "1.0.9"
rand = "0.8.3"
thiserror = "1.0.30"
tracing = "0.1.29"
derive_more = "0.99.17"
lru = "0.7.2"

selendra-node-subsystem = { package = "selendra-node-subsystem", path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-metrics = { path = "../metrics" }
selendra-node-network-protocol = { path = "../network/protocol" }
selendra-primitives = { path = "../../primitives" }
selendra-node-primitives = { path = "../primitives" }
selendra-overseer = { path = "../overseer" }
metered-channel = { path = "../metered-channel" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.9.0"
futures = { version = "0.3.21", features = ["thread-pool"] }
log = "0.4.13"
selendra-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
lazy_static = "1.4.0"
selendra-primitives-test-helpers = { path = "../../primitives/test-helpers" }
