[package]
name = "selendra-gossip-support"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }

selendra-node-network-protocol = { path = "../protocol" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-primitives = { path = "../../../../primitives" }

futures = "0.3.8"
tracing = "0.1.25"
