[package]
name = "indracore-node-core-candidate-selection"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
thiserror = "1.0.23"

sp-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }

indracore-primitives = { path = "../../../../primitives" }
indracore-node-subsystem = { path = "../../subsystem" }
indracore-node-primitives = { path = "../../primitives" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.4" }
