[package]
name = "selendra-node-core-candidate-selection"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
thiserror = "1.0.23"

sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
