[package]
name = "selendra-node-core-av-store"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
futures-timer = "3.0.2"
kvdb = "0.9.0"
thiserror = "1.0.23"
tracing = "0.1.26"
bitvec = "0.20.1"

parity-scale-codec = { version = "2.0.0", features = ["derive"] }
erasure = { package = "selendra-erasure-coding", path = "../../../erasure-coding" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-overseer = { path = "../../overseer" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }

[dev-dependencies]
log = "0.4.13"
env_logger = "0.8.2"
assert_matches = "1.4.0"
kvdb-memorydb = "0.9.0"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
parking_lot = "0.11.1"
