[package]
name = "selendra-node-subsystem-util"
version = "0.1.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.15"
futures-timer = "3.0.2"
itertools = "0.10"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
parking_lot = { version = "0.11.1", optional = true }
pin-project = "1.0.7"
rand = "0.8.3"
thiserror = "1.0.23"
tracing = "0.1.26"
derive_more = "0.99.11"
lru = "0.6.6"

selendra-node-primitives = { path = "../primitives" }
selendra-node-subsystem = { path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-metrics = { path = "../metrics" }
selendra-node-network-protocol = { path = "../network/protocol" }
selendra-primitives = { path = "../../primitives" }
selendra-overseer = { path = "../overseer" }
metered-channel = { path = "../metered-channel"}

sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

[dev-dependencies]
assert_matches = "1.4.0"
async-trait = "0.1.42"
env_logger = "0.8.4"
futures = { version = "0.3.15", features = ["thread-pool"] }
log = "0.4.13"
parking_lot = "0.11.1"
selendra-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
