[package]
name = "selendra-node-core-chain-selection"
version = "0.1.4"
authors = ["Selendra info@selendra.org"]
description = "Chain Selection Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.17"
futures-timer = "3"
tracing = "0.1.28"
kvdb = "0.10.0"
thiserror = "1.0.26"
parity-scale-codec = "2"

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
parking_lot = "0.11"
assert_matches = "1"
kvdb-memorydb = "0.10.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }