[package]
name = 'selendra-parachain-runtime'
version = '0.1.0'
authors = ["Selendra <info@selendra.org>"]
description = "Simple runtime used by the rococo parachain(s)"
edition = '2018'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
parachain-info = { path = "../pallets/parachain-info", default-features = false }
smallvec = "1.6.1"
hex-literal = { version = '0.3.1', optional = true }

# Substrate dependencies
sp-std = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-api = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-io = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-version = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-runtime = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-core = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-session = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-offchain = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-block-builder = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-transaction-pool = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-inherents = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
sp-consensus-aura = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }

frame-benchmarking = { git = "https://github.com/selendra/substrate", optional = true, default-features = false, branch = "0.1.0-tn3" }
frame-system-benchmarking = { git = "https://github.com/selendra/substrate", optional = true, default-features = false, branch = "0.1.0-tn3" }
frame-support = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
frame-executive = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
frame-system = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
frame-system-rpc-runtime-api = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-assets = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-aura = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-authorship = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-balances = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-multisig = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-proxy = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-randomness-collective-flip = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-session = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-sudo = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-timestamp = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-transaction-payment = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-uniques = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
pallet-utility = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }

node-primitives = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }
max-encoded-len = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn3" }

# Cumulus dependencies
cumulus-pallet-aura-ext = { path = "../../modules/cumulus/pallets/aura-ext", default-features = false }
cumulus-pallet-parachain-system = { path = "../../modules/cumulus/pallets/parachain-system", default-features = false }
cumulus-primitives-core = { path = "../../modules/cumulus/primitives/core", default-features = false }
cumulus-primitives-utility = { path = "../../modules/cumulus/primitives/utility", default-features = false }
cumulus-pallet-dmp-queue = { path = "../../modules/cumulus/pallets/dmp-queue", default-features = false }
cumulus-pallet-xcmp-queue = { path = "../../modules/cumulus/pallets/xcmp-queue", default-features = false }
cumulus-pallet-xcm = { path = "../../modules/cumulus/pallets/xcm", default-features = false }
pallet-collator-selection = { path = "../../modules/cumulus/pallets/collator-selection", default-features = false }
selendra-parachain-common = { path = "../common", default-features = false }

# Selendra dependencies
selendra-parachain = { path = "../../modules/parachain", default-features = false }
selendra-runtime-common = { path = "../../runtime/common", default-features = false }
xcm = { path = "../../modules/xcm", default-features = false }
xcm-builder = { path = "../../modules/xcm/xcm-builder", default-features = false }
xcm-executor = { path = "../../modules/xcm/xcm-executor", default-features = false }
pallet-xcm = { path = "../../modules/xcm/pallet-xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
hex = "0.4.3"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }

[features]
default = [ "std" ]
runtime-benchmarks = [
	'hex-literal',
	'sp-runtime/runtime-benchmarks',
	'xcm-builder/runtime-benchmarks',
	'frame-benchmarking',
	'frame-system-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system/runtime-benchmarks',
	'pallet-assets/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-multisig/runtime-benchmarks',
	'pallet-proxy/runtime-benchmarks',
	'pallet-uniques/runtime-benchmarks',
	'pallet-utility/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'pallet-xcm/runtime-benchmarks',
	'pallet-collator-selection/runtime-benchmarks',
]
std = [
	"codec/std",
	"serde",
	"log/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-assets/std",
	"pallet-authorship/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-session/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-uniques/std",
	"pallet-utility/std",
	"parachain-info/std",
	"cumulus-pallet-aura-ext/std",
	"pallet-collator-selection/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"sp-consensus-aura/std",
	"node-primitives/std",
	"selendra-parachain-common/std",
]