[package]
name = "erasure_coding_fuzzer"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
selendra-erasure-coding = { path = ".." }
honggfuzz = "0.5"
primitives = { package = "selendra-node-primitives", path = "../../../node/primitives/" }

[[bin]]
name = "reconstruct"
path = "src/reconstruct.rs"

[[bin]]
name = "round_trip"
path = "src/round_trip.rs"

[workspace]
