[package]
name = "selendra-rpc-core-trace"
version = '0.6.0'
authors = ["Selendra <info@selendra.org>"]
edition = '2018'


[dependencies]
ethereum-types = "0.11.0"
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = { version = "0.3.1", features = ["compat"] }
selendra-rpc-primitives-debug = { path = "../../../rpc/debug" }