[package]
name = "selendra-rpc"
version =  "0.1.0-tn4"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.1.0"
selendra-primitives = { path = "../../primitives" }
sc-client-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-api = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-consensus = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-chain-spec = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-consensus-babe-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-consensus-epochs = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-finality-grandpa = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-finality-grandpa-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
sc-sync-state-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
pallet-mmr-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
pallet-transaction-payment-rpc = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
parity-scale-codec = { version = "2.0.0", default-features = false }
sp-block-builder = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn4" }
beefy-gadget = { git = "https://github.com/selendra/grandpa-bridge-gadget", branch = "0.1.0-tn4" }
beefy-gadget-rpc = { git = "https://github.com/selendra/grandpa-bridge-gadget", branch = "0.1.0-tn4" }
