[package]
name = "staking-miner"
version = "0.9.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
tokio = { version = "0.2", features = ["macros"] }
log = "0.4.11"
env_logger = "0.8.3"
structopt = "0.3.0"
jsonrpsee-ws-client = { version = "0.2.0", default-features = false, features = ["tokio02"] }
jsonrpsee-types = { version = "0.2.0" }
jsonrpsee = "=0.2.0-alpha.6"
serde_json = "1.0"
serde = "1.0.0"
hex = "0.4.0"
lazy_static = "1.4.0"
paste = "1.0.5"
thiserror = "1.0.0"

remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }


frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

core-primitives = { package = "selendra-core-primitives", path = "../../primitives/core-primitives" }

runtime-common = { package = "selendra-runtime-common", path = "../../runtime/common" }
selendra-runtime = { path = "../../runtime/selendra" }

[dev-dependencies]
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
