[package]
name = "selendra-node-core-backing"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
erasure-coding = { package = "selendra-erasure-coding", path = "../../../modules/erasure-coding" }
statement-table = { package = "selendra-statement-table", path = "../../../modules/statement-table" }
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
tracing = "0.1.29"
thiserror = "1.0.30"

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
futures = { version = "0.3.21", features = ["thread-pool"] }
assert_matches = "1.4.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../primitives/test-helpers" }
