[package]
name = "selendra-rpc-core-txpool"
version = '0.6.0'
authors = ["Selendra <info@selendra.org>"]
edition = '2018'


[dependencies]
ethereum = { version = "0.7.1", default-features = false, features = ["with-codec"] }
ethereum-types = "0.11.0"
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

fc-rpc-core = { git = "https://github.com/selendra/frontier", branch = "0.1.0" }
