[package]
name = "xcm-procedural"
version = "0.1.0"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.30"
quote = "1.0.10"
syn = "1.0.82"
