[package]
name = "selendra-statement-distribution"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.26"
selendra-primitives = { path = "../../../../primitives" }
sp-staking = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3", default-features = false }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sc-network = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.6.1"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

[dev-dependencies]
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sp-tracing = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
sc-keystore = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn3" }
futures-timer = "3.0.2"
