[package]
name = "indracore-overseer"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
client = { package = "sc-client-api", git = "https://github.com/selendra/substrate", branch = "master" }
futures = "0.3.12"
futures-timer = "3.0.2"
tracing = "0.1.25"

indracore-node-primitives = { package = "indracore-node-primitives", path = "../primitives" }
indracore-node-subsystem-util = { path = "../subsystem-util" }
indracore-primitives = { path = "../../primitives" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../subsystem" }

[dev-dependencies]
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
indracore-node-network-protocol = { path = "../network/protocol" }
futures = { version = "0.3.12", features = ["thread-pool"] }
femme = "2.1.1"
kv-log-macro = "1.0.7"
assert_matches = "1.4.0"
