[package]
name = "selendra-collator-protocol"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
always-assert = "0.1.2"
futures = "0.3.15"
futures-timer = "3"
thiserror = "1.0.23"
tracing = "0.1.26"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
# sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

selendra-primitives = { path = "../../../primitives" }
selendra-node-network-protocol = { path = "../../network/protocol" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }

[dev-dependencies]
log = "0.4.13"
env_logger = "0.8.4"
assert_matches = "1.4.0"

sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"], branch = "polkadot-v0.9.9" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

selendra-subsystem-testhelpers = { package = "selendra-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
