[package]
name = "test-parachain-halt"
version = "0.1.0-tn3"
authors = ["Selendra <info@selendra.org>"]
description = "Test parachain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = [ "std" ]
std = []
