[package]
name = "cumulus-pallet-parachain-system"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Base pallet for cumulus-based parachains"

[dependencies]
# Cumulus dependencies
cumulus-primitives-core = { path = "../../primitives/core", default-features = false }
cumulus-primitives-parachain-inherent = { path = "../../primitives/parachain-inherent", default-features = false }

# Indracore dependencies
indracore-parachain = { path = "../../../parachain", default-features = false, features = [ "wasm-api" ] }

# Substrate dependencies
frame-support = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
pallet-balances = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-core = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-inherents = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-io = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-std = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-runtime = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-version = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
frame-system = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-state-machine = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-trie = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }
sp-externalities = { git = "https://github.com/selendra/substrate", default-features = false, branch = "master" }

# Other Dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
serde = { version = "1.0.101", optional = true, features = ["derive"] }
hash-db = { version = "0.15.2", default-features = false }
log = { version = "0.4.14", default-features = false }
memory-db = { version = "0.26.0", default-features = false }
trie-db = { version = "0.22.0", default-features = false }
environmental = { version = "1.1.2", default-features = false }

[dev-dependencies]

[features]
default = [ "std" ]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"pallet-balances/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"hash-db/std",
	"log/std",
	"memory-db/std",
	"trie-db/std",
	"sp-state-machine/std",
	"sp-trie/std",
	"sp-externalities/std",
	"frame-system/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-parachain-inherent/std",
	"environmental/std",
]
