[package]
name = "indracore-pov-distribution"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
thiserror = "1.0.23"
tracing = "0.1.22"
# tracing-futures = "0.2.4"

indracore-primitives = { path = "../../../primitives" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-node-network-protocol = { path = "../../network/protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.8.1"
log = "0.4.13"

sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "master" }

indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
