[package]
name = "selendra-node-network-protocol"
version = "0.2.2"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
strum = { version = "0.23", features = ["derive"] }
derive_more = "0.99.17"
futures = "0.3.21"
thiserror = "1.0.30"
async-trait = "0.1.52"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-jaeger = { path = "../../jaeger" }

sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
