
[package]
name = "selendra-node-core-dispute-participation"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
thiserror = "1.0.23"
tracing = "0.1.26"

selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-primitives = { path = "../../../../primitives" }

[dev-dependencies]
assert_matches = "1.5.0"
parity-scale-codec = "2.0.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers"}
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }