version: '3'
services:
  selendra:
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
    image: selendra/selendrachain:latest
    volumes:
      - "selendra-data:/data"
    command: |
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-cors all
      --prometheus-external

volumes:
  selendra-data:
