[package]
name = "test-parachain-adder-collator"
version =  "0.1.0-tn5"
authors = ["Selendra <info@selendra.org>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[[bin]]
name = "adder_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
futures = "0.3.15"
futures-timer = "3.0.2"
log = "0.4.13"
structopt = "0.3.21"

test-parachain-adder = { path = ".." }
selendra-primitives = { path = "../../../../../primitives" }
selendra-cli = { path = "../../../../../bin/cli" }
selendra-service = { path = "../../../../../bin/service" }
selendra-node-primitives = { path = "../../../../node/primitives" }
selendra-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
selendra-node-core-pvf = { path = "../../../../node/core/pvf" }

[dev-dependencies]
selendra-parachain = { path = "../../../../parachain" }
selendra-test-service = { path = "../../../../../bin/test/service" }

substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

tokio = { version = "0.2", features = ["macros"] }
