[package]
name = "test-parachain-adder-collator"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[[bin]]
name = "adder_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
futures = "0.3.19"
futures-timer = "3.0.2"
log = "0.4.13"
structopt = "0.3.25"

test-parachain-adder = { path = ".." }
selendra-primitives = { path = "../../../../../primitives" }
selendra-cli = { path = "../../../../../selendra-chains/bin/cli" }
selendra-service = { path = "../../../../../selendra-chains/node/service", features = ["cardamom-native"] }
selendra-node-primitives = { path = "../../../../../system-node/primitives" }
selendra-node-subsystem = { path = "../../../../../system-node/subsystem" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
selendra-node-core-pvf = { path = "../../../../../system-node/core/pvf" }

[dev-dependencies]
selendra-parachain = { path = "../../.." }
selendra-test-service = { path = "../../../../../selendra-chains/node/test/service" }

substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

tokio = { version = "1.15", features = ["macros"] }
