[package]
name = "selendra-node-core-approval-voting"
version = "0.1.4"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[dependencies]
futures = "0.3.17"
futures-timer = "3.0.2"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["bit-vec", "derive"] }
tracing = "0.1.29"
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
lru = "0.7.0"
merlin = "2.0"
schnorrkel = "0.9.1"
kvdb = "0.10.0"
derive_more = "0.99.17"

sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false, features = ["full_crypto"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-overseer = { path = "../../overseer" }
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-jaeger = { path = "../../jaeger" }

[dev-dependencies]
parking_lot = "0.11.1"
rand_core = "0.5.1"
assert_matches = "1.4.0"
kvdb-memorydb = "0.10.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "master" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

