[package]
name = "selendra-node-core-runtime-api"
version = "0.1.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.28"
memory-lru = "0.1.0"
parity-util-mem = { version = "0.10.0", default-features = false }

sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }

selendra-primitives = { path = "../../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
futures = { version = "0.3.17", features = ["thread-pool"] }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
selendra-node-primitives = { path = "../../primitives" }
