[package]
name = "indracore-node-network-protocol"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
strum = { version = "0.20", features = ["derive"] }
futures = "0.3.12"
thiserror = "1.0.23"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }

indracore-primitives = { path = "../../../primitives" }
indracore-node-primitives = { path = "../../primitives" }
indracore-node-jaeger = { path = "../../jaeger" }


