[package]
name = "selendra-node-core-dispute-coordinator"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
tracing = "0.1.31"
parity-scale-codec = "3.0.0"
kvdb = "0.11.0"
thiserror = "1.0.30"
lru = "0.7.3"
fatality = "0.0.6"

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }


[dev-dependencies]
kvdb-memorydb = "0.11.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
assert_matches = "1.4.0"
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../primitives/test-helpers" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
