[package]
name = "selendra-node-core-provisioner"
version = "0.1.4"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.29"
thiserror = "1.0.30"
futures-timer = "3.0.2"
selendra-primitives = { path = "../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
bitvec = { version = "0.20.1", default-features = false, features = [] }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
