[package]
name = "selendra-node-core-provisioner"
version = "0.1.7"
authors = ["Selendra info@selendra.org"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
futures = "0.3.17"
tracing = "0.1.29"
thiserror = "1.0.30"
futures-timer = "3.0.2"
selendra-primitives = { path = "../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
