[package]
name = "cumulus-primitives-core"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-std = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-api = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-runtime = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
sp-trie = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }
frame-support = { git = "https://github.com/selendra/substrate", default-features = false, branch = "0.1.0-tn4" }

# Selendra dependencies
selendra-parachain = { path = "../../../parachain", default-features = false }
selendra-primitives = { path = "../../../../primitives", default-features = false }
selendra-core-primitives = { path = "../../../../primitives/core-primitives", default-features = false }
xcm = { path = "../../../xcm", default-features = false }

# Other dependencies
impl-trait-for-tuples = "0.2.1"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [ "derive" ] }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-std/std",
	"selendra-primitives/std",
	"selendra-parachain/std",
	"selendra-core-primitives/std",
	"sp-runtime/std",
	"sp-trie/std",
	"sp-api/std",
	"frame-support/std",
]
