[package]
name = "selendra-node-jaeger"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Selendra Jaeger primitives"

[dependencies]
async-std = "1.8.0"
mick-jaeger = "0.1.4"
lazy_static = "1.4"
parking_lot = "0.11.1"
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../primitives" }
sc-network = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "0.1.0-tn1" }
thiserror = "1.0.23"
log = "0.4.13"
parity-scale-codec = { version = "2.0.0", default-features = false }
