[package]
name = "selendra-node-core-chain-api"
version = "0.1.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
tracing = "0.1.26"
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
selendra-primitives = { path = "../../../primitives" }
selendra-subsystem = { package = "selendra-node-subsystem", path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

[dev-dependencies]
futures = { version = "0.3.15", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "2.0.0"
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
