[package]
name = "parachains-common"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Logic which is common to all parachain runtimes"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "2.3.0", features = ["derive"], default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }

# Substrate dependencies
sp-consensus-aura = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
sp-std = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false  }
sp-io = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
frame-executive = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
frame-support = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
frame-system = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
pallet-asset-tx-payment = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
pallet-assets = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
pallet-authorship = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
pallet-balances = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
sp-runtime = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
sp-core = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}

# Selendra dependencies
selendra-runtime-common = { path = "../../../selendra-chains/runtime/common", default-features = false  }
selendra-primitives = { path = "../../../primitives", default-features = false  }
xcm = { path = "../../../modules/xcm", default-features = false  }
xcm-executor = { path = "../../../modules/xcm/xcm-executor", default-features = false  }

# Local dependencies
pallet-collator-selection = { path = "../../../modules/cumulus/pallets/collator-selection", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
pallet-authorship = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-consensus-aura/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-asset-tx-payment/std",
	"pallet-collator-selection/std",
	"pallet-assets/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"selendra-runtime-common/std",
	"selendra-primitives/std",
]
